#
# PLUGINS OPTIONS
#
offscreenreload           0
inputmacro                0
timer                     0
hiscore                   0
dummy                     0
cheat                     0
discord                   0
cheatfind                 0
autofire                  0
gdbstub                   0
portname                  0
layout                    1
data                      1
timecode                  0
console                   0
